site_name: Modern Physics through Nobel Prizes
site_url: https://modphysnobel.github.io
site_author: Baroja Weber, J.R., Lizárraga-Celaya, C.
site_description: >-
  Book that explores and describes Modern Physics from the scientific contributions of known scientists that have received Nobel Prizes.

# Repository
docs_dir: docs/
repo_name: Modern-Physics-through-Nobel-Prizes
repo_url: https://github.com/modphysnobel/modphysnobel.github.io


nav:
  - 'Home':
    - 'Home': index.md
    - 'About': about.md
  - 'Book volumes':
    - 'Motion': vol-I/volume-I.md
    - 'Energy': vol-II/volume-II.md
    - 'Waves': vol-III/volume-III.md
    - 'Universe': vol-IV/volume-IV.md

theme: 
  name: material

  # setting features for the navigation tab
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.expand
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - toc.integrate
    # - toc.follow
  hide:
    - navigation
  favicon: assets/favicon.png  

# Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: orange 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Regular

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/modphysnobel  
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0009-0009-4616-9243
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorge-barojas-weber-b8926534/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-0893-4268
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/carloslizarragac/
#    - icon: fontawesome/brands/facebook
#      link: https://www.facebook.com/carlos.lizarragac/
#    - icon: fontawesome/brands/mastodon
#      link: https://mastodon.online/@clizarraga
    

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
#    - mkdocstrings
#    - git-revision-date
#    - mkdocs-jupyter:
#          include_source: True
#         ignore_h1_titles: True     
# Copyright
copyright: 'Creative Commons BY-NC-SA 4.0'


